# Personal Introduction {.unnumbered}

Hi, my name is Liu Yihan and I received my undergraduate degree in Land Resource Management from China University of Geosciences (Beijing). During my undergraduate studies, I have developed a strong interest in using data to analyse urban issues and have been involved in a variety of activities. For example, on campus, I worked with several classmates with the same interest to study the coupled relationship between urbanisation efficiency and eco-efficiency in the Yellow River Basin under the guidance of the supervisor, and wrote and published a [paper](https://www.mdpi.com/2073-445X/11/6/882) about it. Meanwhile, I had an internship in a planning company and participated in the project of assessing the slow-moving network system in Changping District, Beijing and the research project of assessing the carbon reduction potential of urban community life circle planning.

My interest in learning new technologies and using data to identify and solve urban problems attracted me to choose the Remote Sensing of Cities and Environments course, where I hope to improve my ability to process and analyse remotely sensed data for application in my future career. And this website is my study diary containing my weekly learning experiences for this course, happy reading!
